# Sử dụng PHP CLI
FROM php:8.1-cli

# Đặt thư mục làm việc bên trong container
WORKDIR /app

# Copy toàn bộ thư mục bài tập vào container
COPY . /app

# Giữ container chạy và cho phép truy cập vào terminal
CMD ["bash"]
