version: '3.8'

services:
  php-advance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-advance
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - memcached
    env_file:
      - .env
    command: php -S 0.0.0.0:8000 -t /app

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
