version: '3.8'

services:
  php-ex1:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./:/usr/src/myapp
    networks:
      - my-network
    # command: sh -c "php ./public-html/index.php && tail -f /dev/null"

  # apache-ex1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-apache
  #   ports:
  #     - "8024:80"
  #   networks:
  #     - my-network

networks:
  my-network:
