version: '3.8'

services:
  php-rest-api:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - anonymous-vendor:/var/www/html/src/vendor # chặn mount vendor giữa host và container
    depends_on:
      - db-rest-api
    networks:
      - app-api-network

  nginx-rest-api:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8097:80"
    depends_on:
      - php-rest-api
    networks:
      - app-api-network

  db-rest-api:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-rest-api
      MYSQL_USER: laravel-rest-api
      MYSQL_PASSWORD: laravel-rest-api
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-api-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
    networks:
      - app-api-network

volumes:
  db_data:
  anonymous-vendor:

networks:
  app-api-network:
    driver: bridge
