version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: mvc_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mvc_network

  php:
    build:
      context: ./docker/php
    container_name: mvc_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - mvc_network

  mysql:
    image: mysql:8.0
    container_name: mvc_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mvc_network

networks:
  mvc_network:
    driver: bridge

volumes:
  mysql_data:
