version: '3.8'

services:
  node:
    image: node:16
    working_dir: /var/www/html
    volumes:
      - ./laravel/source:/var/www/html
    networks:
      - app-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./laravel/source:/var/www/html
    depends_on:
      - redis
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/source:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-login
      MYSQL_USER: laravel-login
      MYSQL_PASSWORD: laravel-login
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
