version: '3.8'

services:
  php-api:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./laravel/source:/var/www/html
    depends_on:
      - redis
      - db-api
    networks:
      - app-network

  nginx-api:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/source:/var/www/html
    ports:
      - "8089:80"
    depends_on:
      - php-api
    networks:
      - app-network

  db-api:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-api
      MYSQL_USER: laravel-api
      MYSQL_PASSWORD: laravel-api
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
